apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  name: "mnist"
spec:
  predictor:
    pytorch:
      storageUri: gs://kfserving-examples/models/torchserve/image_classifier
      # storageUri: pvc://model-pv-claim