apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: torchserve-kfserving
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vishal-wiai/playground.git
    targetRevision: HEAD
    path: serving/torchserve-kfserving
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: admin
  syncPolicy:
    automated:
      prune: false
      selfHeal: false